# Generated by Django 5.1.1 on 2024-09-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ImageField(default='default-images/artist-profile.png', upload_to='')),
                ('first_name', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
