# Generated by Django 5.1.1 on 2024-09-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artistcataloguecategory_artist_otp_artistcatalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
